### PR TITLE
enum pending values

### PR DESCRIPTION
**Pull request by yoshuawuyts**
Allows checking which other nodes a node is waiting for. Useful to show progress more accurately. Thanks!

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
cc/ @jbergstroem could you take a look? Thanks!

**Comment by jbergstroem** [comment]
sounds/looks good to me (sorry for the delay)

**Comment by yoshuawuyts** [comment]
@jbergstroem no worries; thanks for the review! :grin:

**Comment by yoshuawuyts** [comment]
`v3.1.0` :tada:

**Pull request merged**
